#!/bin/bash -e

if [ -f "/var/lib/stsbl/repoconfig.sh" ]
then
  . /var/lib/stsbl/repoconfig.sh
fi

if [ -v REPOUPDATEMODE ] && ! [ "$REPOUPDATEMODE" = "" ]
then
  echo "$REPOUPDATEMODE"
else
  echo "unknown"
fi
